version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - YAGPT_API_KEY=${YAGPT_API_KEY}
    volumes:
      - .:/app
    restart: always